### ISSUE TITLE
vim diff show errors: missing argument: ctermbg=

### ISSUE THREAD

**Issue by livelazily** [joshdick/onedark.vim#109] opened 2017-09-18 00:44 UTC
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: 

iTerm2 with tumux 2.5  
$TERM xterm-256color

### Output From `vim --version`

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 13 2017 04:07:30)
MacOS X (unix) version
Included patches: 1-1098
Compiled by travis@Traviss-Mac-657.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +float           +mouse_urxvt     -tcl
+autocmd         +folding         +mouse_xterm     +termguicolors
+balloon_eval    -footer          +multi_byte      +terminal
+browse          +fork()          +multi_lang      +terminfo
++builtin_terms  +fullscreen      -mzscheme        +termresponse
+byte_offset     -gettext         +netbeans_intg   +textobjects
+channel         -hangul_input    +num64           +timers
+cindent         +iconv           +odbeditor       +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +transparency
+cmdline_compl   +jumplist        +perl/dyn        +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
+file_in_path    +mouse_sgr       +tag_old_static  
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib   -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE 
```

### Issue Description

vim diff file will show this error message:
```
Error detected while processing function <SNR>76_set_highlight_colors[37]..<SNR>76_add_to_highlight_group:
line    1:
E417: missing argument: ctermbg=
Error detected while processing function <SNR>76_set_highlight_colors[38]..<SNR>76_add_to_highlight_group:
line    1:
E417: missing argument: ctermbg=
Press ENTER or type command to continue
```
It show up every time while I diff with files

**Comment by joshdick** [comment] 2017-09-18 03:56
I am unable to reproduce this when invoking `vimdiff`.

How have you installed `onedark.vim`? Are you sure you're using the latest version of it?

**Comment by livelazily** [comment] 2017-09-18 04:01
I installed `onedark.vim` using [vim-plug](https://github.com/junegunn/vim-plug#installation).

The `onedark.vim` is the latest version.

Here is my vim files:
https://github.com/livelazily/dotvim

**Comment by joshdick** [comment] 2017-09-18 04:13
Your config looks correct.

Can you paste the output of:

```bash
cd ~/.vim/bundle/onedark.vim
git status
git log --oneline | head -n 1
```

**Comment by livelazily** [comment] 2017-09-18 04:15
Console output:

```
~ ❯❯❯ cd ~/.vim/bundle/onedark.vim
~/.v/b/onedark.vim ❯❯❯ git status                                                                              master
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
~/.v/b/onedark.vim ❯❯❯ git log --oneline | head -n 1                                                           master
1552d3e In diff mode, for cursorline, use underline styling instead of background styling to improve readability.
```

**Comment by joshdick** [comment] 2017-09-18 04:21
Also looks correct. Are you starting vimdiff manually, or through another program like Git? Have you tried commenting out other plugins?

**Comment by livelazily** [comment] 2017-09-18 04:28
Just using `vimdiff file1 file2` from the cli.
If I change to other color scheme in the vimrc file, and retry to diff files, it will not show the error.

**Comment by joshdick** [comment] 2017-09-18 15:24
I was able to reproduce the issue using your `.vimrc`.

I tried commenting out other plugins in your `.vimrc` I like I suggested, and it looks like there's a conflict with `unblevable/quick-scope`; if I remove that plugin, vimdiff works fine with `onedark.vim`.

I haven't yet looked into what parts of the code are actually conflicting.

**Comment by joshdick** [comment] 2017-09-18 15:28
After further investigation, seems like the issue is with `quick-scope`; there's a PR open to fix it: https://github.com/unblevable/quick-scope/pull/30

In light of that, going to close this issue.

**Closed by joshdick** 2017-09-18 15:28 UTC
