### ISSUE TITLE
Git commit comment highlighting

### ISSUE THREAD

**Issue by shawnohare** [joshdick/onedark.vim#11] opened 2016-02-17 06:37 UTC
I noticed after 5640329f7a694f3e7bf200869faac1a9bc4c6098 that my Git commit coloring appeared a bit off.  In particular, comments and regular text are the same color.  While I primarily use neovim + iterm2 (and the associated onedark themes), I notice the same issue with regular vim and a minimal vimrc.  For example:

<img width="720" alt="screen shot 2016-02-16 at 10 22 27 pm" src="https://cloud.githubusercontent.com/assets/3992436/13101478/ee712f86-d4fb-11e5-950a-5abda28aa1ac.png"> 

However, tweaking the Git highlighting to use `s:comment_grey` where previously no color was specified, such as:
```
call s:h("gitcommitComment", {"fg": s:comment_grey })
call s:h("gitcommitUnmerged", { "fg": s:green })
call s:h("gitcommitOnBranch", { "fg": s:comment_grey })
call s:h("gitcommitBranch", { "fg": s:purple })
call s:h("gitcommitDiscardedType", { "fg": s:red })
call s:h("gitcommitSelectedType", { "fg": s:green })
call s:h("gitcommitHeader", { "fg": s:comment_grey })
call s:h("gitcommitUntrackedFile", { "fg": s:cyan })
call s:h("gitcommitDiscardedFile", { "fg": s:red })
call s:h("gitcommitSelectedFile", { "fg": s:green })
call s:h("gitcommitUnmergedFile", { "fg": s:yellow })
call s:h("gitcommitFile", { "fg": s:comment_grey })
```
results in something more like what I would expect:
<img width="720" alt="screen shot 2016-02-16 at 10 28 24 pm" src="https://cloud.githubusercontent.com/assets/3992436/13101584/b9858f32-d4fc-11e5-888b-e87dbc263d0d.png">

I'm not entirely sure what colors were intended for git commits, or how the above modification affects other configurations, or whether this is an issue with the color scheme or simply my personal configs.

**Comment by joshdick** [comment] 2016-02-22 15:17
I am unable to reproduce this behavior using a minimal Vim configuration with master (5640329), the commit message is white as expected without modifying the theme.

I tested with NeoVim 0.1.2 as well as Vim 7.4 patches (1-1301).

Are you sure you're using the latest iTerm color scheme (last changed in 4bb1115?)

**Comment by shawnohare** [comment] 2016-02-22 22:03
It looks like the iterm2 theme was up to date.  I retried things with a vim/neovim init file consisting of
```
syntax on
colorscheme onedark
```
using vim v7.4 (patches 1-1345), neovim v0.1.3-128-gf887037, and neovim v0.1.2 and the iterm2 nightly build.

Vanilla vim looked like it had no issues, but both versions of neovim still exhibit the issue.  Perhaps it's something to do with the iterm2 nightly builds?  Vanilla vim (with the onedark theme) looked ok even in the default OS X terminal, but neovim had more serious issues.

I'm willing to accept that the issue is entirely with my setup, so feel free to close the issue.  If I discover anything I can chime in again.

**Comment by joshdick** [comment] 2016-02-22 22:06
The only other thing I can think of is iTerm's "Draw bold text in bright colors" setting, which also shouldn't be the culprit here since the text isn't bold.

Closing this for now as you suggested; thanks for the report in any case!

**Closed by joshdick** 2016-02-22 22:06 UTC
